### ISSUE TITLE
When qmenu-vm is running, xfce workspace navigation keys stop working

### ISSUE THREAD

**Issue by brendanhoar** [sine3o14nnae/qmenu#4]
First - this is a lovely alternative, thank you for the work.

The issue I ran into is that I am fairly reliant on ctrl-alt right-arrow and ctrl-alt left-arrow as my primary navigation from workspace to workspace under Qubes R4.0x. 

However, while qmenu-vm is executing in dom0, these keys are ignored. In order to navigate to other workspaces, I must exit qmenu-vm.

This is somewhat disconcerting. While hitting esc at the top level (or ctrl-c anyway) will exit qmenu allowing me to navigate again...I feel reluctant to use a tool that is capturing or blocking these important key sequences.

Brendan

**Comment by 3o14r473** [comment]
Thank you, I am pleased that you enjoy it.


This is something that I would like to be different too, but I have to disappoint you. _qmenu_ has no control over it, as _dmenu_ is responsible for this behaviour and does not provide any configuration option to handle this in a different way. 

Of course, forking and modifying _dmenu_ is an option but this is beyond the scope of _qmenu_. 

On a side note, you could go ahead and see if [rofi](https://github.com/davatorium/rofi) behaves differently. If so, you could simply replace _dmenu_ with _rofi_ and use _qmenu_ that way. This would be easy to configure, as you would only have to install _rofi_ and symlink _/usr/bin/dmenu_ to _/usr/bin/rofi_.

**Comment by 3o14r473** [comment]
@brendanhoar 
The **very** obvious alternative I failed to mention is simply patching your copy of _dmenu_.  

Take a look at https://tools.suckless.org/dmenu/patches/ and search some other sites, maybe there is already a patch that implements your desired feature.
