### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by har-pi** [sine3o14nnae/qmenu#6]
Heya guys, just found out qmenu. Gonna give it a try within the day as I think it will ease my i3 setup on qubes.

Please add some screeshots to portray the project a little better

**Comment by 3o14r473** [comment]
Checkout `qmenu-am --focused`. It works great with tiling window managers like i3.

I will probably add some screenshots to external documentation, after qmenu is made available in the qubes repositories. However, I want the readme to remain rather minimal.
